### PR TITLE
Update validate-xmllint-installation.ts

### PR DESCRIPTION
**Pull request by BPanchal-Fintech**

### CODE REVIEW

**Comment by aautio** [comment]
Hi @BPanchal-Fintech. What is the intention of these changes?

**Comment by BPanchal-Fintech** [comment]
@aautio Because I am getting error while installing this package.

**Error: Failed to validate xmllint installation. All xml validations will fail.**

If you complete this PR then it should resolve issue.

**npm xmllint --version**

**Comment by aautio** [comment]
@BPanchal-Fintech if you get an error while installing it likely means that you do not have `xmllint` installed in your system. Thus the package will not work.

The idea for this package is to invoke `xmllint` for XML validations. Thus it has to be present in the system.

Would you please paste the output of `xmllint --version` here?

**Comment by KBPatel-Fintech** [comment]
@aautio 
Yes xmllint is already installed.
xmllint version: **6.13.4**

xmllint --version is not working as it is not recognized as the name of cmdlet.
That is why I want to append npm before executing the xmllint --version.

**Comment by aautio** [comment]
@KBPatel-Fintech The version `6.13.4` of xmllint does not exist. That `6.13.4` is the version of your `npm`. It is different program.

Proof: try this one: `npm foobar --version` and you'll see a similar output of `6.13.4`.

The expected output of `xmllint --version` looks something along these lines:

```$ xmllint --version
xmllint: using libxml version 20904
   compiled with: Threads Tree Output Push Reader Patterns Writer SAXv1 FTP HTTP DTDValid HTML Legacy C14N Catalog XPath XPointer XInclude ICU ISO8859X Unicode Regexps Automata Expr Schemas Schematron Modules Debug Zlib ```

**Pull request closed without merging**
